AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/LineLength:
  Exclude:
    - 'ruby_audit.gemspec'

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  AllowedMethods:
    - describe

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'exe/ruby-audit'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
