AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Exclude:
    - 'ruby_audit.gemspec'

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  IgnoredMethods:
    - describe

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'exe/ruby-audit'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
